### ISSUE TITLE
Stealth mode

### ISSUE THREAD

**Issue by pcarranza** [gomeeseeks/meeseeks-box#18]
In some cases this makes sense:

- Make the bot appear as not connected
- Only attend users that have some form of permission, this can be obtained through the groups. Any other user will be flatly ignored.

**Comment by pcarranza** [comment]
According to slack API we need to set user presence to "away"

Besides that, we need to add a matcher that would drop the message unless the talking user is registered in a group (any group)

**Comment by omame** [comment]
Done in https://github.com/gomeeseeks/meeseeks-box/pull/32?

**Comment by pcarranza** [comment]
Yes, done!
