### ISSUE TITLE
Add aliases per user

### ISSUE THREAD

**Issue by pcarranza** [gomeeseeks/meeseeks-box#21]

**Comment by pcarranza** [comment]
cc/ @omame

**Comment by omame** [comment]
I'm thinking of creating a new bolt bucket for users and then a sub-bucket for aliases. The reason for this is that we'll probably use this for storing other user-related things: it's better to structure this out for scaling now than paying a high tax later. We could even move the tokens here if we want to.

**Comment by pcarranza** [comment]
tokens are tricky because we need to find them by token ID. if we would like to do that we will need to have some form of index. let's not focus on that now.

**Comment by pcarranza** [comment]
so, this will be like aliases/username/alias ?

**Comment by omame** [comment]
I was more thinking about `users/aliases/alias` and then filter based on the username.

**Comment by pcarranza** [comment]
so, a static bucket for the first level, then the username (which is variable), then inside it a bucket for the aliases? or do you want a first level bucket with the username?

**Comment by omame** [comment]
In #31 I've implemented this with `aliases/<user id>/<alias>`.
