### ISSUE TITLE
Keep an admin channel

### ISSUE THREAD

**Issue by omame** [gomeeseeks/meeseeks-box#8]
As a way of making it all visible, use a channel as the administration channel in which to report events, like when a client box joins the master, or when they are down, or when a permission is granted. Whatever matters.

This channel should be set in configuration and could also be an IM with a single user.

**Comment by pcarranza** [comment]
I think that with Prometheus metrics and all the logging and auditory we have in place this is not necessary anymore. WDYT @omame ?

**Comment by omame** [comment]
Hehe. I like the "kill all the logs" approach.
Let's close this and we'll reopen should the need for logging arise.
