### ISSUE TITLE
Enable remote execution mode

### ISSUE THREAD

**Issue by omame** [gomeeseeks/meeseeks-box#9]
This is a complex one.

The idea is that we could start a meeseeks-box in remote mode, this will remove all the builtin commands and only allow to execute local commands, meaning that the box would not have any permission model, or even persistence.

This would require a token (or client cert) and will use grpc in streaming mode to talk to a master meeseeks-box to which it would register.

On connection the client box will register the "remote" commands on the master, and then the master will start directing commands to the remotes.

The master will then keep the permissions and the persistence of the remote commands execution, and will also use a heartbeat message to ensure that they are still there.

**Comment by pcarranza** [comment]
@omame I think we can call this done and start iterating with the simple design we have right now?
